_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.17
            "5": 0.19.10
            "8":
                - 1
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 72
dropout:
    value: 0.4
epochs:
    value: 1
fc_layer_size:
    value: 512
learning_rate:
    value: 0.08963112369012943
optimizer:
    value: sgd
