_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.17
            "5": 0.19.10
            "8":
                - 1
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 128
dropout:
    value: 0.5376637450868731
epochs:
    value: 5
lr:
    value: 0.001
